import type { LanguageModelV1, LanguageModelV1CallWarning } from '@ai-sdk/provider'
import { convertToFlowiseMessage } from './convert-to-flowise-message'
// import { convertFlowiseResponseToAiSdkMessage } from './convert-to-ai-sdk-message'
import { FlowiseClient } from './flowise-client'
import type { FlowisePredictionRequest } from './types'

export class FlowiseChatModel implements LanguageModelV1 {
    readonly specificationVersion = 'v1' as LanguageModelV1['specificationVersion']
    readonly defaultObjectGenerationMode = 'json'
    readonly supportsImageUrls = false
    readonly modelId = 'flowise-chatflow'

    readonly chatflowId: string
    readonly client: FlowiseClient

    constructor(chatflowId: string, client: FlowiseClient) {
        this.chatflowId = chatflowId
        this.client = client
    }

    get provider(): string {
        return 'flowise.ai'
    }

    supportsUrl(url: URL): boolean {
        return url.protocol === 'https:' || url.protocol === 'http:'
    }

    private getArgs({ prompt }: Parameters<LanguageModelV1['doGenerate']>[0]) {
        const warnings: LanguageModelV1CallWarning[] = []

        const baseArgs: FlowisePredictionRequest = {
            question: convertToFlowiseMessage(prompt),
            chatId: undefined // Will be generated by Flowise
        }

        return {
            args: baseArgs,
            warnings
        }
    }

    async doGenerate(options: Parameters<LanguageModelV1['doGenerate']>[0]): Promise<Awaited<ReturnType<LanguageModelV1['doGenerate']>>> {
        const { args, warnings } = this.getArgs(options)

        try {
            const response = await this.client.predict(this.chatflowId, args)

            // Convert Flowise response to AI SDK message format for metadata
            // const aiSdkMessage = convertFlowiseResponseToAiSdkMessage(response)

            return {
                text: response.text,
                finishReason: 'stop',
                usage: {
                    promptTokens: 0, // Flowise doesn't provide token usage
                    completionTokens: 0
                },
                warnings,
                rawCall: {
                    rawPrompt: args,
                    rawSettings: {
                        chatflowId: this.chatflowId
                    }
                }
            }
        } catch (error) {
            throw new Error(`Flowise API error: ${error instanceof Error ? error.message : String(error)}`)
        }
    }

    async doStream(options: Parameters<LanguageModelV1['doStream']>[0]): Promise<Awaited<ReturnType<LanguageModelV1['doStream']>>> {
        const { args, warnings } = this.getArgs(options)

        try {
            const flowiseStream = await this.client.predictStream(this.chatflowId, args)

            // Transform Flowise stream to AI SDK compatible stream
            const stream = new ReadableStream({
                async start(controller) {
                    const reader = flowiseStream.getReader()

                    try {
                        // eslint-disable-next-line no-constant-condition
                        while (true) {
                            const { done, value } = await reader.read()
                            if (done) break

                            // Only pass through text-delta chunks that match AI SDK format
                            if (value && typeof value === 'object' && value.type === 'text-delta' && value.textDelta) {
                                controller.enqueue({
                                    type: 'text-delta',
                                    textDelta: value.textDelta
                                })
                            }
                        }
                        controller.close()
                    } catch (error) {
                        controller.error(error)
                    } finally {
                        reader.releaseLock()
                    }
                }
            })

            return {
                stream,
                warnings,
                rawCall: {
                    rawPrompt: args,
                    rawSettings: {
                        chatflowId: this.chatflowId
                    }
                }
            }
        } catch (error) {
            throw new Error(`Flowise streaming error: ${error instanceof Error ? error.message : String(error)}`)
        }
    }
}
