name: PR Preview Package

on:
  pull_request_review:
    types: [submitted]

jobs:
  preview:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Publish preview package with pkg.pr.new
        run: bunx pkg-pr-new publish
